// <auto-generated />
// AUTO-GENERATED by tools/gen_leve_tables.py from XIVAPI v2 game data. DO NOT EDIT BY HAND.
// Regenerate:  python tools/gen_leve_tables.py
// Validate:    python tools/validate_leve_tables.py   (add --check to fail CI on drift)
//
// This is currently REFERENCE + VALIDATION data: the hand-authored Data/Leve*.cs tables
// remain the runtime source of truth. Wiring LeveRunner to dispatch off BookLeves.Rule
// (keyed by leve id, name as fallback) is the planned P0 rule-dispatch refactor.

using System.Collections.Generic;

namespace Relicable.Data;

public static class GeneratedLeveTables
{
    public sealed record ItemLure(uint ItemId, string PrimeTargetName, string EmergeTargetName, string ItemSourceName);
    public sealed record BookLeve(uint LeveId, string Name, string Rule, string Handler);

    // BattleLeveHunt item-lure leves. Derived from BattleLeve.LeveData: source = ItemsInvolvedQty>0
    // entry (the enemy killed for the item), ItemId = its ItemsInvolved, emerge = ToDoNumberInvolved>0
    // + BNpcName entry (the slay target), prime = the shared "prime location" EObj marker.
    public static readonly IReadOnlyDictionary<string, ItemLure> ItemLures =
        new Dictionary<string, ItemLure>(System.StringComparer.OrdinalIgnoreCase)
        {
            ["Big, Bad Idea"] = new ItemLure(2000880u, "prime location", "Foul River hapalit", "ragged hippogryph"),
            ["Don't Forget to Cry"] = new ItemLure(2000872u, "prime location", "balor", "balor's bell"),
            ["Got a Gut Feeling about This"] = new ItemLure(2000880u, "prime location", "stegotaur", "downcast hippocerf"),
        };

    // CompanyLeveSummon named targets. Value = highest-EnemyLevel CompanyLeveStruct BNpcName.
    public static readonly IReadOnlyDictionary<string, string> NamedTargets =
        new Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)
        {
            ["If You Put It That Way"] = "frost aevis",
            ["Someone's Got a Big Mouth"] = "Mimas",
            ["Who Writes History"] = "Okeanos the Red",
        };

    // BattleLeveRound "make the rounds" leves. Value is the marker object name (a constant).
    public static readonly IReadOnlyDictionary<string, string> Destinations =
        new Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)
        {
            ["Circling the Ceruleum"] = "Destination",
            ["Put Your Stomp on It"] = "Destination",
            ["The Area's a Bit Sketchy"] = "Destination",
        };

    // Every Animus (Trials of the Braves) book leve, its game rule, and the LeveRunner handler
    // that rule dispatches to. The seed for the rule-dispatch refactor and coverage validation.
    public static readonly IReadOnlyList<BookLeve> BookLeves = new BookLeve[]
    {
        new(643u, "Subduing the Subprime", "BattleLeveSweep", "RunFight"),
        new(644u, "Necrologos: Pale Oblation", "BattleLeveOrb", "RunFight+Parchment"),
        new(645u, "Don't Forget to Cry", "BattleLeveHunt", "RunItemLure"),
        new(646u, "Circling the Ceruleum", "BattleLeveRound", "RunDestination"),
        new(647u, "Someone's in the Doghouse", "BattleLeveGuide", "RunEscort"),
        new(649u, "Necrologos: Whispers of the Gem", "BattleLeveOrb", "RunFight+Parchment"),
        new(650u, "Got a Gut Feeling about This", "BattleLeveHunt", "RunItemLure"),
        new(652u, "The Area's a Bit Sketchy", "BattleLeveRound", "RunDestination"),
        new(657u, "Necrologos: The Liminal Ones", "BattleLeveOrb", "RunFight+Parchment"),
        new(658u, "Big, Bad Idea", "BattleLeveHunt", "RunItemLure"),
        new(659u, "Put Your Stomp on It", "BattleLeveRound", "RunDestination"),
        new(848u, "Someone's Got a Big Mouth", "CompanyLeveSummon", "RunFight+NamedTarget"),
        new(849u, "An Imp Mobile", "CompanyLevePenetration", "RunFight (DEFERRED)"),
        new(853u, "Yellow Is the New Black", "CompanyLeveInterception", "RunFight"),
        new(855u, "The Bloodhounds of Coerthas", "CompanyLeveProtection", "RunFight+Anchor"),
        new(859u, "No Big Whoop", "CompanyLevePenetration", "RunFight (DEFERRED)"),
        new(860u, "If You Put It That Way", "CompanyLeveSummon", "RunFight+NamedTarget"),
        new(863u, "One Big Problem Solved", "CompanyLeveInterception", "RunFight"),
        new(865u, "Go Home to Mama", "CompanyLeveProtection", "RunFight+Anchor"),
        new(868u, "The Awry Salvages", "CompanyLeveProtection", "RunFight+Anchor"),
        new(870u, "Get off Our Lake", "CompanyLeveInterception", "RunFight"),
        new(873u, "Who Writes History", "CompanyLeveSummon", "RunFight+NamedTarget"),
        new(875u, "The Museum Is Closed", "CompanyLeveProtection", "RunFight+Anchor"),
    };
}
