using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Relicable.Data;

// The allowlist that decides what auto-discard is ALLOWED to touch: item ids known to drop
// from an enemy, generated by tools/gen_mob_drops.py from Garland Tools' item.drops field
// and shipped as Data/catalogs/mob_drop_items.json.
//
// WHY AN ALLOWLIST. Auto-discard used to select items with a NEGATIVE filter -- white,
// stackable, vendor price <= 100, not equippable, not usable -- on the assumption that this
// described mob-drop clutter. It does not: ~5,400 items match it, among them the entire
// Trials of the Braves crafting pipeline (Aged Eye of Fire, Aged Pestle Pieces, Pumice,
// Belah'dian Silver, Electrum Sand, Silver Ingot, Sunstone ...), and the plugin deleted them.
// A negative filter fails OPEN: anything the rules did not anticipate gets destroyed.
//
// So the question is now positive and has to be answered before anything is deleted: does
// this item drop from an enemy? An id that is absent -- because it is crafted, gathered,
// fished, vendored, desynthed, a quest item, or simply not in the table -- is NOT discarded.
// Missing data therefore means "keep", which is the direction this feature has to fail in.
//
// The load is lazy and latches only on success, the same pattern MateriaCatalog and
// RelicWeaponStages use: a read taken before the file is available returns an empty set
// (nothing is discardable) and is retried, rather than freezing an empty catalogue in place.
public static class MobDropCatalog
{
    private sealed class Payload
    {
        [JsonPropertyName("items")] public List<Entry> Items { get; set; } = new();
    }

    private sealed class Entry
    {
        [JsonPropertyName("id")] public uint Id { get; set; }
        [JsonPropertyName("name")] public string? Name { get; set; }
    }

    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
    };

    private static readonly HashSet<uint> Empty = new();
    private const long RetryMs = 5000;

    private static HashSet<uint>? _ids;
    private static long _retryAt;
    private static bool _warned;

    // True when the item is known to drop from an enemy. FALSE while the catalogue is
    // unavailable, so a missing or unreadable file disables discarding entirely instead of
    // quietly reverting to the old delete-anything-cheap behaviour.
    public static bool IsMobDrop(uint itemId)
        => itemId != 0 && Ids().Contains(itemId);

    // How many ids the catalogue holds; 0 means "not loaded", which the configuration window
    // surfaces so an install with a missing data file does not look like a silent no-op.
    public static int Count => Ids().Count;

    private static HashSet<uint> Ids()
    {
        if (_ids is { Count: > 0 })
            return _ids;

        var now = Environment.TickCount64;
        if (now < _retryAt)
            return Empty;
        _retryAt = now + RetryMs;

        try
        {
            var dir = Plugin.PluginInterface.AssemblyLocation.DirectoryName ?? ".";
            var path = Path.Combine(dir, "Data", "catalogs", "mob_drop_items.json");
            if (!File.Exists(path))
            {
                if (!_warned)
                {
                    _warned = true;
                    Plugin.Log.Warning(
                        "Relicable: mob-drop catalogue (Data/catalogs/mob_drop_items.json) is missing; "
                        + "auto-discard will not delete anything until it is present.");
                }
                return Empty;
            }

            var payload = JsonSerializer.Deserialize<Payload>(File.ReadAllText(path), Options);
            var set = new HashSet<uint>();
            foreach (var e in payload?.Items ?? new List<Entry>())
                if (e.Id != 0)
                    set.Add(e.Id);

            if (set.Count > 0)
            {
                _ids = set;
                Plugin.Log.Information($"Relicable: mob-drop catalogue loaded ({set.Count} enemy-drop items).");
            }
            return set;
        }
        catch (Exception ex)
        {
            if (!_warned)
            {
                _warned = true;
                Plugin.Log.Warning($"Relicable: could not read the mob-drop catalogue: {ex.Message}");
            }
            return Empty;
        }
    }
}
