using System;
using System.Security.Cryptography;
using System.Text;

namespace Relicable.Licensing;

// Early Alpha access codes.
//
// SHARED SOURCE. This one file is compiled into BOTH the plugin and the offline
// key generator (tools/RelicableKeygen links it via <Compile Include=".."/>), so the
// minting side and the verifying side can never drift apart. Change it in one place
// and both rebuild against the change.
//
// ---------------------------------------------------------------------------
// Scheme
// ---------------------------------------------------------------------------
// A code is an ECDSA (NIST P-256 / SHA-256) signature over a small plaintext
// payload. The private key lives only on the maintainer's machine; the plugin
// ships nothing but the PUBLIC key, so a code cannot be forged by anyone who
// decompiles the DLL. The payload names the person the code was issued to and
// the date it stops working.
//
//     RLC1.<base64url(payload)>.<base64url(signature)>
//
//     payload   = "<owner>|<expiry-days-since-epoch>|<serial>"   (UTF-8)
//     signed    = "RLC1|" + payload                              (domain separator)
//     signature = ECDSA-P256-SHA256, IEEE P1363 fixed-width (64 bytes)
//
// The owner is shown permanently in the plugin window ("Alpha access: <owner>").
// That is the anti-sharing mechanism: a leaked code visibly names the person it
// was issued to, in the UI of everyone running it. The serial makes two codes for
// the same owner distinct, so one can be revoked without burning the other.
//
// ---------------------------------------------------------------------------
// What this is NOT
// ---------------------------------------------------------------------------
// This is distribution control, not security. Any client-side gate can be removed
// by patching the assembly, and this one is no exception. It exists to keep an
// unfinished alpha from spreading casually, and to make a leak attributable -- not
// to stop a determined attacker. Do not build anything on it that assumes secrecy.
public static class AlphaCode
{
    // Wire-format prefix. Bump to RLC2 if the payload layout ever changes, so old
    // codes fail cleanly with a version message instead of a confusing parse error.
    public const string Prefix = "RLC1";

    // ---------------------------------------------------------------------------
    // The alpha signing PUBLIC key: X.509 SubjectPublicKeyInfo, base64.
    //
    // Generated by `RelicableKeygen init`, which writes the matching PRIVATE key to
    // keys/relicable-alpha.key (gitignored). Replacing this constant invalidates
    // every code ever issued -- that is the emergency lever if the private key leaks.
    // ---------------------------------------------------------------------------
    public const string PublicKeyBase64 =
        "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEosKfOxPqeKDQk+8WodkJZhLICxaUDf/CN2j/llfWEcGZV6KWLhtxOggF74/oClRZlhfVDP5i5ddZ2WmW+N3ebw==";

    // Serials of individually revoked codes, shipped with each plugin update. A code
    // whose serial is listed here fails validation even though its signature is valid
    // and it has not expired. Use it when a specific code is known to have leaked.
    private static readonly string[] RevokedSerials =
    {
        // "a1b2c3d4",
    };

    // Days since 1970-01-01 UTC, the payload's expiry unit. Chosen over a Unix
    // timestamp purely to keep the code string short; day granularity is plenty.
    private static readonly DateTime Epoch = new(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

    // Bounds of what Epoch.AddDays can represent. Outside these, AddDays throws
    // ArgumentOutOfRangeException -- and the day count comes straight out of an
    // attacker- or typo-controlled payload that is parsed BEFORE the signature is
    // checked, so it has to be range-checked rather than trusted.
    // -719162 = 0001-01-01, 2932896 = 9999-12-31, both relative to 1970-01-01.
    private const int MinEpochDays = -719162;
    private const int MaxEpochDays = 2932896;

    public static int ToEpochDays(DateTime utc) => (int)(utc.Date - Epoch).TotalDays;

    // Returns false instead of throwing when days cannot be represented as a DateTime.
    public static bool TryFromEpochDays(int days, out DateTime value)
    {
        if (days < MinEpochDays || days > MaxEpochDays)
        {
            value = default;
            return false;
        }

        value = Epoch.AddDays(days);
        return true;
    }

    // ---------------------------------------------------------------------------
    // Verification
    // ---------------------------------------------------------------------------

    // Validates a code. Never throws: every failure path returns false with a
    // user-facing reason, because this runs on the plugin's UI thread against
    // arbitrary pasted text.
    public static bool TryValidate(string? code, out AlphaLicense license, out string error)
        => TryValidate(code, DateTime.UtcNow, PublicKeyBase64, out license, out error);

    // Testable overload: explicit clock and key. The generator uses it to verify a
    // freshly minted code against the key it just wrote.
    public static bool TryValidate(
        string? code, DateTime utcNow, string publicKeyBase64,
        out AlphaLicense license, out string error)
    {
        license = default;
        error = string.Empty;

        if (!TryParse(code, out var payload, out var signature, out error))
            return false;

        if (!TryReadPayload(payload, out license, out error))
            return false;

        // Signature first: an expired-but-authentic code and a forged code should not
        // be distinguishable by which error they produce.
        byte[] publicKey;
        try
        {
            publicKey = Convert.FromBase64String(publicKeyBase64);
        }
        catch (FormatException)
        {
            error = "This build has no valid alpha signing key compiled in. Please report it.";
            return false;
        }

        bool ok;
        try
        {
            using var ecdsa = ECDsa.Create();
            ecdsa.ImportSubjectPublicKeyInfo(publicKey, out _);
            var signed = Encoding.UTF8.GetBytes(Prefix + "|" + payload);
            ok = ecdsa.VerifyData(
                signed, signature, HashAlgorithmName.SHA256,
                DSASignatureFormat.IeeeP1363FixedFieldConcatenation);
        }
        catch (CryptographicException)
        {
            // A malformed key or signature blob lands here. Treat it as "not valid"
            // rather than surfacing a crypto exception to the user.
            ok = false;
        }

        if (!ok)
        {
            error = "That code is not valid. Check for a missing character when copying.";
            license = default;
            return false;
        }

        foreach (var revoked in RevokedSerials)
        {
            if (string.Equals(revoked, license.Serial, StringComparison.OrdinalIgnoreCase))
            {
                error = "That code has been revoked. Contact the developer for a new one.";
                license = default;
                return false;
            }
        }

        if (utcNow.Date > license.Expires.Date)
        {
            error = $"That code expired on {license.Expires:yyyy-MM-dd}. Contact the developer for a new one.";
            // Deliberately keep the parsed license so the UI can name the owner and
            // date of an expired code -- it is authentic, just past its window.
            return false;
        }

        return true;
    }

    // Splits "RLC1.<payload>.<sig>" and base64url-decodes the two parts. Tolerant of
    // whitespace and line breaks, because codes get pasted out of Discord messages.
    private static bool TryParse(string? code, out string payload, out byte[] signature, out string error)
    {
        payload = string.Empty;
        signature = Array.Empty<byte>();
        error = string.Empty;

        if (string.IsNullOrWhiteSpace(code))
        {
            error = "Enter your Early Alpha access code.";
            return false;
        }

        var cleaned = Strip(code!);
        var parts = cleaned.Split('.');
        if (parts.Length != 3)
        {
            error = "That does not look like an access code. It should start with \"RLC1.\".";
            return false;
        }

        if (!string.Equals(parts[0], Prefix, StringComparison.Ordinal))
        {
            error = $"Unsupported code format \"{parts[0]}\". This build expects {Prefix} codes; you may need a newer Relicable.";
            return false;
        }

        if (!TryFromBase64Url(parts[1], out var payloadBytes) || !TryFromBase64Url(parts[2], out signature))
        {
            error = "That code is damaged. Copy it again, making sure you get the whole line.";
            return false;
        }

        try
        {
            payload = Encoding.UTF8.GetString(payloadBytes);
        }
        catch (ArgumentException)
        {
            error = "That code is damaged. Copy it again, making sure you get the whole line.";
            return false;
        }

        return true;
    }

    // Reads "<owner>|<expiryDays>|<serial>". The owner may not contain '|', which the
    // generator enforces at mint time.
    private static bool TryReadPayload(string payload, out AlphaLicense license, out string error)
    {
        license = default;
        error = string.Empty;

        var fields = payload.Split('|');
        if (fields.Length != 3
            || !int.TryParse(fields[1], out var expiryDays)
            || !TryFromEpochDays(expiryDays, out var expires))
        {
            error = "That code is damaged. Copy it again, making sure you get the whole line.";
            return false;
        }

        license = new AlphaLicense(fields[0], expires, fields[2]);
        return true;
    }

    // ---------------------------------------------------------------------------
    // Minting -- used only by the offline generator, but it lives here so the format
    // is defined exactly once. The plugin never calls this (it has no private key).
    // ---------------------------------------------------------------------------

    public static string Mint(ECDsa privateKey, string owner, DateTime expiresUtc, string serial)
    {
        if (owner.Contains('|'))
            throw new ArgumentException("Owner may not contain '|' (the payload field separator).", nameof(owner));
        if (serial.Contains('|'))
            throw new ArgumentException("Serial may not contain '|' (the payload field separator).", nameof(serial));

        var payload = $"{owner}|{ToEpochDays(expiresUtc)}|{serial}";
        var signed = Encoding.UTF8.GetBytes(Prefix + "|" + payload);
        var signature = privateKey.SignData(
            signed, HashAlgorithmName.SHA256,
            DSASignatureFormat.IeeeP1363FixedFieldConcatenation);

        return $"{Prefix}.{ToBase64Url(Encoding.UTF8.GetBytes(payload))}.{ToBase64Url(signature)}";
    }

    // Decodes a code's payload WITHOUT checking the signature. For the generator's
    // `inspect` command only -- never call this to decide access.
    public static bool TryInspect(string? code, out AlphaLicense license, out string error)
    {
        license = default;
        return TryParse(code, out var payload, out _, out error)
            && TryReadPayload(payload, out license, out error);
    }

    // ---------------------------------------------------------------------------
    // base64url (RFC 4648 section 5): '+' -> '-', '/' -> '_', padding dropped. Keeps
    // the code safe to paste through chat clients that mangle '+' or wrap on '/'.
    // ---------------------------------------------------------------------------

    private static string ToBase64Url(byte[] bytes)
        => Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');

    private static bool TryFromBase64Url(string value, out byte[] bytes)
    {
        bytes = Array.Empty<byte>();
        if (value.Length == 0)
            return false;

        var padded = value.Replace('-', '+').Replace('_', '/');
        switch (padded.Length % 4)
        {
            case 2: padded += "=="; break;
            case 3: padded += "="; break;
            case 1: return false; // never a valid base64 length
        }

        try
        {
            bytes = Convert.FromBase64String(padded);
            return true;
        }
        catch (FormatException)
        {
            return false;
        }
    }

    // Removes every whitespace character, so a code that got line-wrapped by Discord
    // or picked up a trailing newline from a copy still validates.
    private static string Strip(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
            if (!char.IsWhiteSpace(c))
                sb.Append(c);
        return sb.ToString();
    }
}

// A validated (or at least authentic) alpha code's contents.
public readonly record struct AlphaLicense(string Owner, DateTime Expires, string Serial)
{
    public bool IsPresent => !string.IsNullOrEmpty(Owner);

    // Whole days remaining, floored at zero. Drives the "expires in N days" nudge.
    public int DaysRemaining(DateTime utcNow) => Math.Max(0, (int)(Expires.Date - utcNow.Date).TotalDays);
}
